### ISSUE TITLE
搭建失败下docker

### ISSUE THREAD

**Issue by APPX-Studio** [Gouryella/ChatTTS-webui#1]
<img width="1078" alt="image" src="https://github.com/Gouryella/ChatTTS-webui/assets/49307767/16c44abc-cd36-4f76-8f4e-1dce6c58b513">

**Comment by APPX-Studio** [comment]
大佬的显卡什么型号。会不会被玩坏啊

**Comment by Gouryella** [comment]
从截图来看，还在拉取镜像文件，等待即可。使用gpu的话，需要安装nvidia-container-toolkit。https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
