### ISSUE TITLE
docker搭建失败了

### ISSUE THREAD

**Issue by A13788899580** [Gouryella/ChatTTS-webui#2]
大佬，在第二步出现如下提示，帮忙看看什么问题啊：
ERROR: failed to solve: process "/bin/sh -c npm install -g yarn && yarn install &&     git clone https://github.com/2noise/ChatTTS.git api/ChatTTS &&     git clone https://huggingface.co/2Noise/ChatTTS.git api/models &&     pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 128

**Comment by Gouryella** [comment]
联网失败，重新执行操作
