### ISSUE TITLE
Install failed in MacOS 14.5 + M2 chip

### ISSUE THREAD

**Issue by aispin** [Gouryella/ChatTTS-webui#4]
# OS Info

macOS 14.5 + M2

## Issue

When running `yes | conda install pytorch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 pytorch-cuda=12.1 -c pytorch -c nvidia`, it throws error as below:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch-cuda=12.1*

Current channels:

  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - defaults

```

**Comment by Gouryella** [comment]
use ` conda install pytorch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 -c pytorch`
