### ISSUE TITLE
远程访问时，没有显示生成的声音文件，不能播放，也不能下载声音文件

### ISSUE THREAD

**Issue by vincent7f** [Gouryella/ChatTTS-webui#5]
如题，以下截图。
正常情况下，在“生成”按钮下方，应该有声音文件的播放、波形图和下载按钮的。但我通过IP访问时，“生成“按钮在点击后，下方仍是空白的。
该服务在本地访问是正常的，即127.0.0.1:3000。

补充一点，我是通过Docker安装使用的，命令就是官网上的Docker安装命令。

![image](https://github.com/Gouryella/ChatTTS-webui/assets/45114756/bd91306d-3441-4ca7-b0c0-ae03b7c05ba7)

**Comment by Gouryella** [comment]
修改js代码，改成服务端ip
